"""Enrolling students in a course and getting enrolled courses of student by student ID

Revision ID: cd29e312b1bf
Revises: a6acedfbb898
Create Date: 2023-09-06 13:56:13.462584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd29e312b1bf'
down_revision: Union[str, None] = 'a6acedfbb898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
